spring:
  application:
    name: "configserver"
  profiles:
    active: git
  #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/Prathihaspodduturi/microservices-configserver-configurations.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
          #native:
          #search-locations: "file:///E://config"


        #search-locations: "classpath:/config"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true

encrypt:
  key: "idejdjwopjkdwppowkows"

server:
  port: 8071
